### 0.导入包并设置GPU

In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'
os.environ['CUDA_VISIABLE_DEVICES']='O'

import tensorflow as tf 
import numpy as np
phy_gpus = tf.config.experimental.list_physical_devices('GPU')
for gpu in phy_gpus:
    tf.config.experimental.set_memory_growth(gpu,True)

### 1.创建tensor

In [2]:
a = tf.constant([[1,2],[3,4]])
b = a*a
print(a)
print(b)
print(type(a))
print(type(b))

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 1  4]
 [ 9 16]], shape=(2, 2), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


###  2.tensor vs ndarray

In [3]:
c = np.array([[1,2],[3,4]])
d = tf.constant(c)
print(c)
print(d)
print(type(c))
print(type(d))

[[1 2]
 [3 4]]
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
<class 'numpy.ndarray'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


### 3.tensor->ndarray

In [4]:
e = d.numpy()
print(e)
print(type(e))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


### 4.cpu or gpu

In [5]:
print(d.device)
print(tf.config.list_physical_devices('CPU'))
print(tf.config.list_physical_devices('GPU'))

/job:localhost/replica:0/task:0/device:CPU:0
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


### 5.Variable

In [6]:
f = tf.Variable([[1,2],[3,4]])
print(f)
print(type(f))

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>


### 6.修改tensor的值
#### tf.constant不可修改

In [7]:
g = tf.constant(100)
print(g)
g.assign(20)

tf.Tensor(100, shape=(), dtype=int32)


AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

#### tf.Variable可以修改

In [8]:
h = tf.Variable(100)
print(h)
h.assign(50)
print(h)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=100>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=50>
